# -*- coding: utf-8 -*-
############################################################
#
# Autogenerated by the KBase type compiler -
# any changes made here will be overwritten
#
############################################################

from __future__ import print_function
# the following is a hack to get the baseclient to import whether we're in a
# package or not. This makes pep8 unhappy hence the annotations.
try:
    # baseclient and this client are in a package
    from .baseclient import BaseClient as _BaseClient  # @UnusedImport
except:
    # no they aren't
    from baseclient import BaseClient as _BaseClient  # @Reimport


class taxonomy_service(object):

    def __init__(
            self, url=None, timeout=30 * 60, user_id=None,
            password=None, token=None, ignore_authrc=False,
            trust_all_ssl_certificates=False,
            auth_svc='https://kbase.us/services/authorization/Sessions/Login'):
        if url is None:
            raise ValueError('A url is required')
        self._service_ver = None
        self._client = _BaseClient(
            url, timeout=timeout, user_id=user_id, password=password,
            token=token, ignore_authrc=ignore_authrc,
            trust_all_ssl_certificates=trust_all_ssl_certificates,
            auth_svc=auth_svc)

    def search_taxonomy(self, params, context=None):
        """
        :param params: instance of type "DropDownItemInputParams" ->
           structure: parameter "private" of type "bool" (A binary boolean),
           parameter "public" of type "bool" (A binary boolean), parameter
           "search" of String, parameter "limit" of Long, parameter "start"
           of Long
        :returns: instance of type "DropDownData" -> structure: parameter
           "num_of_hits" of Long, parameter "hits" of list of type
           "DropDownItem" -> structure: parameter "label" of String,
           parameter "id" of String, parameter "category" of String
        """
        return self._client.call_method(
            'taxonomy_service.search_taxonomy',
            [params], self._service_ver, context)

    def create_taxonomy(self, params, context=None):
        """
        :param params: instance of type "CreateTaxonomyInputParams" ->
           structure: parameter "scientific_name" of String, parameter
           "taxonomic_id" of Long, parameter "kingdom" of String, parameter
           "domain" of String, parameter "genetic_code" of Long, parameter
           "aliases" of list of String, parameter "scientific_lineage" of
           list of String, parameter "workspace_name" of String
        :returns: instance of type "CreateTaxonomyOut" -> structure:
           parameter "ref" of type "ObjectReference" (workspace ref to an
           object), parameter "scientific_name" of String
        """
        return self._client.call_method(
            'taxonomy_service.create_taxonomy',
            [params], self._service_ver, context)

    def get_taxonomies_by_id(self, params, context=None):
        """
        :param params: instance of type "GetTaxonomiesIdInputParams" ->
           structure: parameter "taxonomy_object_refs" of list of type
           "ObjectReference" (workspace ref to an object)
        :returns: instance of type "GetTaxonomiesOut" -> structure: parameter
           "taxon_objects" of list of type "Taxon" -> structure: parameter
           "children" of list of type "ObjectReference" (workspace ref to an
           object), parameter "decorated_children" of list of type
           "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_lineage" of
           list of String, parameter "decorated_scientific_lineage" of list
           of type "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_name" of
           String, parameter "taxonomic_id" of Long, parameter "kingdom" of
           String, parameter "domain" of String, parameter "genetic_code" of
           Long, parameter "aliases" of list of String
        """
        return self._client.call_method(
            'taxonomy_service.get_taxonomies_by_id',
            [params], self._service_ver, context)

    def get_taxonomies_by_query(self, params, context=None):
        """
        :param params: instance of type "GetTaxonomiesQueryInputParams" ->
           structure: parameter "search" of String, parameter "limit" of
           Long, parameter "start" of Long
        :returns: instance of type "GetTaxonomiesOut" -> structure: parameter
           "taxon_objects" of list of type "Taxon" -> structure: parameter
           "children" of list of type "ObjectReference" (workspace ref to an
           object), parameter "decorated_children" of list of type
           "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_lineage" of
           list of String, parameter "decorated_scientific_lineage" of list
           of type "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_name" of
           String, parameter "taxonomic_id" of Long, parameter "kingdom" of
           String, parameter "domain" of String, parameter "genetic_code" of
           Long, parameter "aliases" of list of String
        """
        return self._client.call_method(
            'taxonomy_service.get_taxonomies_by_query',
            [params], self._service_ver, context)

    def get_genomes_for_taxonomy(self, params, context=None):
        """
        :param params: instance of type "GetGenomesTaxonomyInputParams" ->
           structure: parameter "search" of String, parameter "limit" of
           Long, parameter "start" of Long
        :returns: instance of type "GetTaxonomiesOut" -> structure: parameter
           "taxon_objects" of list of type "Taxon" -> structure: parameter
           "children" of list of type "ObjectReference" (workspace ref to an
           object), parameter "decorated_children" of list of type
           "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_lineage" of
           list of String, parameter "decorated_scientific_lineage" of list
           of type "TaxonInfo" -> structure: parameter "ref" of type
           "ObjectReference" (workspace ref to an object), parameter
           "scientific_name" of String, parameter "scientific_name" of
           String, parameter "taxonomic_id" of Long, parameter "kingdom" of
           String, parameter "domain" of String, parameter "genetic_code" of
           Long, parameter "aliases" of list of String
        """
        return self._client.call_method(
            'taxonomy_service.get_genomes_for_taxonomy',
            [params], self._service_ver, context)

    def status(self, context=None):
        return self._client.call_method('taxonomy_service.status',
                                        [], self._service_ver, context)
